### ISSUE TITLE
Uh - oh error - Apache Cordova VS 2013,CTP 3.1 project

### ISSUE THREAD

**Issue by aasavad** [brody2consult/cordova-sqlite-storage#237]
Hi,

I tried to add the plugin to Visual Studio 2013,CTP 3.1 Apache Cordova project .On building the project on Windows Phone (Universal ) 8.1, it showed MDAVSCLI : error : Uh oh! 

I cannot add the plugin through CLI as its not a cordova project.Is there any other way to add the plugin to VS project?

Any help would be great.

Thanks!

**Comment by brody2consult** [comment]
Unfortunately that is not enough information. Please describe exactly what kind of a project you had made and how you made it. If you need "manual installation" instructions, I will work on it.

**Comment by aasavad** [comment]
Thanks a lot for the response.

I tried to add the plugin to Visual Studio Ionic Sidemenu Starter template Cordova Project.The plugin was added through Config File -> Custom Plugin option -> Add the plugin thorough GIT . Plugin was added and It showed the error on build (Target Windows Phone Universal).

I added the plugin to a blank cordova project in Visual studio (target platform windows phone universal) and the result was the same.If you could help me in Manual Installation, that would be brilliant .

**Comment by brody2consult** [comment]
I will try my best. This could be a bit of a challenge since I have (only) Visual Studio Express 2013 (without any Ionic or Cordova project option).

This project has a Windows (NT) 8.1-only C++ project for native sqlite3 access. To target Windows Phone Universal, we need a Windows Universal project (actually two projects). I can make this project with Visual Studio Express 2013, but it will not work with the Cordova CLI. I am planning to raise this as a ticket against the Cordova-Windows project.

Can you let me know how quickly you need to get this fixed?

**Comment by aasavad** [comment]
Thanks .As far as I know,u could install the apache cordova extension for Visual studio express.The latest version is CTP 3.1

If you could advise how you can make this work with VS express (from JavaScript),I could proceed with my project .Ionic has not started supporting Windows officially,so we are keeping two source files for ios and windows .I could make the changes to only windows version till this is fixed in official plugin.

It would be great if you can help me with the fix by next week.I could go ahead with manual installation if it takes long time to fix.

**Comment by brody2consult** [comment]
I just published a new version that supports both Windows 8.1 and Windows Phone 8.1 in the `windows` (Universal) target. Unfortunately they do not support all Windows CPU types due to issues with the Cordova CLI (which I will try to get fixed). I have also documented a partially-manual installation procedure that should all Windows CPU types. Please let me know how this works for you.

**Comment by aasavad** [comment]
Thank you.

I added the new version of plugin to a blank Cordova VS Project.It showed the same build error ('Uh Oh') first time.When i tried to build again without making any changes ,it succeeded without any errors.

However when i tried to run this on emulator,it showed the below error -
0x800a138f - JavaScript runtime error: Unable to get property 'openDatabase' of undefined or null reference

I used your same sample code in onDeviceReady() event.

var db = window.sqlitePlugin.openDatabase("Database", "1.0", "Demo", -1); 

I tried the same after adding <script src="SQLitePlugin.js"></script> to index.html but the result was the same.

![sqlite](https://cloud.githubusercontent.com/assets/11210283/7177895/4a56da4c-e422-11e4-8539-a2fa73fde54a.jpg)

**Comment by aasavad** [comment]
This is what I did  -

New Project  - Apache Cordova

![1](https://cloud.githubusercontent.com/assets/11210283/7178022/82241650-e423-11e4-884f-7aed335efd03.jpg)

Adding the Plugin  - 

![2](https://cloud.githubusercontent.com/assets/11210283/7178032/964c38f6-e423-11e4-99d3-d01eb4279333.jpg)

Installed successfully -

![3](https://cloud.githubusercontent.com/assets/11210283/7178043/aa2af9e8-e423-11e4-90a5-39aae2accac4.jpg)

Open database - onDeviceready 
![4](https://cloud.githubusercontent.com/assets/11210283/7178051/b83c2de0-e423-11e4-8e83-2a0c73cc176e.jpg)
Target - Android by default - Build successful

![5](https://cloud.githubusercontent.com/assets/11210283/7178067/cd4ad074-e423-11e4-838b-1dba24457fe9.jpg)

Change Target - Windows Phone (Universal)
![6](https://cloud.githubusercontent.com/assets/11210283/7178084/ea3d5684-e423-11e4-8e52-e1d753e8f729.jpg)

Build error - Uh -Oh
![7](https://cloud.githubusercontent.com/assets/11210283/7178099/012c5c32-e424-11e4-9f0f-53cc28eb12f9.jpg)

Build again - Successful
![8](https://cloud.githubusercontent.com/assets/11210283/7178102/11cd6248-e424-11e4-83fb-1e42fdab7ba3.jpg)

Run -
![9](https://cloud.githubusercontent.com/assets/11210283/7178109/204f40ca-e424-11e4-9273-4ce09e594b03.jpg)

Error -
![10](https://cloud.githubusercontent.com/assets/11210283/7178112/34b7eb98-e424-11e4-94cd-2311529e00eb.jpg)

Is there anything I am missing.I tried to run it on device as well and the app crashes.

**Comment by brody2consult** [comment]
This does look very weird. But I am suspicious that this is caused by the fact that the cordova-windows project does not support all Windows target platforms. I just reported this problem in [Apache CB-8866](https://issues.apache.org/jira/browse/CB-8866) and raised a pull request in apache/cordova-windows#67 to solve this problem.

I recommend that we wait for Cordova-Windows to integrate this fix and then try it again. If they take too long, I am happy to publish the fix in a fork along with instructions how to use it.

**Comment by aasavad** [comment]
That would be great.Thanks a lot Chris.

**Comment by brody2consult** [comment]
I have now published a special version of cordova-windows that supports using this plugin with the `plugman` tool, as I just described in README.md. For now, you will have to use the Cordova `plugman` tool to create your Windows Universal project; using `cordova create` or Visual Studio to create your Cordova project will not be supported until the fix for [Apache CB-8866](https://issues.apache.org/jira/browse/CB-8866) is accepted, integrated, and released by Cordova.

Please let me know if this is working for you or not.

**Comment by aasavad** [comment]
Thanks a lot Chris.
I created a sample project as per your instructions and it worked fine.

Will try to integrate my Ionic project similarly and let you know.

**Comment by aasavad** [comment]
I managed to run a sample ionic project and this version worked fine.I am able to open the db now.

Is sqlcipher supported in this version Chris?

I added the sqlcipher plugin and it showed the error -  Unable to get property 'openDatabase' of undefined or null reference
![sqlcipher](https://cloud.githubusercontent.com/assets/11210283/7322997/80dfc128-eaa3-11e4-9bfa-c55b597f0929.png)

**Comment by brody2consult** [comment]
Not yet-just filed litehelpers/Cordova-sqlcipher-adapter#6. When do you need this?

I am getting ready for a 1-week vacation. If you need the fix soon, I can do this tomorrow night.

**Comment by aasavad** [comment]
Hi Chris,

Could you please do it tomorrow night if its ok.

Once Sqlcipher is sorted,I can start working on modifying the whole Ionic Project  to make it work on windows.

Thanks a million

**Comment by brody2consult** [comment]
I will work on this today and keep you posted.

**Comment by brody2consult** [comment]
I just got sqlcipher working with both Windows 8.1 and Windows Phone 8.1 in this version. Please report whether or not this is whyat you need.

**Comment by aasavad** [comment]
Hi Chris,

Thanks for the quick fix.

I installed the Sqlcipher as per mentioned in https://github.com/litehelpers/Cordova-sqlcipher adapter but got the below error - OPEN database: failed, aborting any pending transactions.

I noticed one more thing,when i connect device to run the project on device,I am not able to see the device option in the target list.Not sure whether i have to do something in VS to enable it.I can see the device option if i select the 'ARM' platform.

![cipher](https://cloud.githubusercontent.com/assets/11210283/7346149/6bd2e30a-ecd3-11e4-8bc3-e097812839d5.png)
![cipher1](https://cloud.githubusercontent.com/assets/11210283/7346187/a6c3501c-ecd3-11e4-8e3b-a03c42bc2e23.png)

**Comment by brody2consult** [comment]
Is it a new database file or do you try to open an existing database file?

**Comment by aasavad** [comment]
This is a new database file.

**Comment by aasavad** [comment]
Tried with another name for db as well.Same result.

![cipher1](https://cloud.githubusercontent.com/assets/11210283/7346326/24c8d38c-ecd5-11e4-9942-e7fffdafed6b.png)

**Comment by aasavad** [comment]
Hi Chris,

When i tried to build the project,I am getting the below error.Its not all the time though.

![cipher2](https://cloud.githubusercontent.com/assets/11210283/7346465/7592ce3e-ecd6-11e4-80df-b71ace1df2db.png)

**Comment by brody2consult** [comment]
Did you do this with a fresh project?

**Comment by aasavad** [comment]
Yes.

I created a new sqlite project using plugman as per the manual installation steps.

Added the sqlcipher plugin using plugman as per the manual installation steps.

Opened the solution using VS 2013,build and run.

**Comment by brody2consult** [comment]
I will look at this later today. It would help me if you can send me a copy of your project.

**Comment by aasavad** [comment]
Thanks Chris.I will send you the project.Can you give me your email id please.

**Comment by brody2consult** [comment]
info@litehelpers.net (you should see it at the end of the readme) or brodybits@litehelpers.net

**Comment by aasavad** [comment]
Sorry Chris.I missed it.

Just sent the source code to your email.

Thanks a lot.

**Comment by brody2consult** [comment]
Looks like your project has both the "normal" sqlite-storage plugin and sqlcipher-adapter plugin installed. This combination is not supported, you have to choose one or the other. Please make a fresh project and try it again.

**Comment by aasavad** [comment]
Hi Chris. 

That worked.

For the projects created using this method, the device is not being listed in Visual Studio .I am able to run the project on emulator but not on a real device.I am new to Visual Studio.Will have to check for solution online.

Thanks a million once again for the help

**Comment by brody2consult** [comment]
> That worked.

Happy to hear!

> For the projects created using this method, the device is not being listed in Visual Studio .I am able to run the project on emulator but not on a real device.I am new to Visual Studio.Will have to check for solution online.

Please post it if you find the solution-it can help others.

I hope they integrate the fix in PR apache/cordova-windows#67 so that we don't have to go through this workaround!

**Comment by aasavad** [comment]
Hi Chris,

Yes.I will post once i find the solution.

One thing I noticed is once you open the db using a particular key , it shouldn't allow the db to be opened with another key (Please correct me if I am wrong).First time i used key  'test' to open the db.Later i changed the key to 'savad',build and tried running the project on emulator and the db was opened.

 First time      var db = window.sqlitePlugin.openDatabase({ name: "cipher.db", key: "test" }); 

 Second time  var db = window.sqlitePlugin.openDatabase({ name: "cipher.db", key: "savad" }); 

The console db path  was same in both cases.

I used Sqlcipher trial version for ios and that version didn't open the db after changing the key value.I tried it on actual device that time.

**Comment by brody2consult** [comment]
> One thing I noticed is once you open the db using a particular key , it shouldn't allow the db to be opened with another key

Correct.

> First time var db = window.sqlitePlugin.openDatabase({ name: "cipher.db", key: "test" });
> 
> Second time var db = window.sqlitePlugin.openDatabase({ name: "cipher.db", key: "savad" });

Can you post your actual code for this?

Two things, if your code does what I think it does:
- In the case of `var db=window.sqlitePlugin.openDatabase...` you get a `db` object synchronously, regardless of whether or not the database is actually opened. If it failed, then every attempt to execute sql statement or transaction will get an error callback.
- If you open a database that is already open, then it will simply give you a working `db` handle object on the already-open database.

This needs to be documented more clearly.

**Comment by aasavad** [comment]
Hi Chris,

This is what I did -

Step 1 - Db key is set as  'firsttest' .The db gets opened successfully as per the console.
![firsttest](https://cloud.githubusercontent.com/assets/11210283/7352770/4b641638-ed06-11e4-877e-592f406aa4bf.png)

Step -2 - Stop debug - Changed the key to 'sectest' ,build and run.The db gets opened successfully.

![sectest](https://cloud.githubusercontent.com/assets/11210283/7352802/8c21f1cc-ed06-11e4-85d0-925ce2da5045.png)

As far as i remember,this was not the case when i did the same on ios .Please correct me if I am wrong.Or this will work correctly only on device?

Thanks!

**Comment by brody2consult** [comment]
Yes if you open a database with an encryption key but write absolutely no data, it is possible that you will get a database file with size of zero which you can then open with a different key!

Please try creating a very simple table and then try it again to open with a different password.

**Comment by brody2consult** [comment]
I was able to reproduce the behavior you observed and will add a test case for it, which I would like to treat with an intermediate priority (when I come back).

**Comment by aasavad** [comment]
Thank you Chris,

I got an update from microsoft team regarding the device not getting listed in VS 2013.

https://social.msdn.microsoft.com/Forums/windowsapps/en-US/cf84a439-d7cd-4023-acd4-6b247a76f471/visual-studio-2013-mixed-platform-doesnt-list-device-option-for-deployment?forum=wpdevelop

I was able to build as ARM and deploy to device after installing SQLite using plugman but the sqlcipher version gives the below error.

![cipher3](https://cloud.githubusercontent.com/assets/11210283/7357226/60e66e6a-ed25-11e4-822d-200a40390902.png)

**Comment by brody2consult** [comment]
I just pushed a fix to the following location: https://github.com/brodybits/Cordova-sqlcipher-adapter-dev

Unfortunately, `plugman uninstall` does not seem to work with the Windows version so you have to try this with a fresh project (yet again).

Please let me know if this works or not. Reference: http://www.monkey-x.com/Community/posts.php?topic=7739

**Comment by brody2consult** [comment]
> I just pushed a fix to the following location: https://github.com/brodybits/Cordova-sqlcipher-adapter-dev

Just checking if it helped or not-maybe it can help others.

I am getting ready for vacation now and cannot make any major changes before next week.

Chris

**Comment by aasavad** [comment]
Hi Chris,

Sorry for the late response.

I am still getting the same error.(earlier the error was fired from both cordovaapp.phone and cordovapp.windows.Now its fired from only cordovapp.windows)

1)Created a new project
2)Installed the plugin using plugman from the new url provided.

![cipher4](https://cloud.githubusercontent.com/assets/11210283/7365473/91dafbf4-ed88-11e4-82d9-7c8f493a7dba.png)

**Comment by brody2consult** [comment]
Can you send me a ZIP with your project again?

**Comment by aasavad** [comment]
Just sent the zip to your email.

**Comment by brody2consult** [comment]
Haha for some reason, it looks like Visual Studio also tries to build the SQLite3 library for Windows (for a "Universal" app), and the problem is actually with building the Windows (desktop) DLL. I also realized that we need the flag for Release version as well.

I will push a new version within the next few minutes and let you know.

**Comment by aasavad** [comment]
Thanks a lot Chris.

**Comment by brody2consult** [comment]
I just pushed an update to https://github.com/litehelpers/Cordova-sqlcipher-adapter that _should_ fix this issue on both Windows & Windows Phone (8.1) build, for both Debug and Release targets. Can you please try it again (in a fresh project, as you know) and let me know if it works or not?

**Comment by aasavad** [comment]
Yes.That works perfect.

Thanks a million for all your help Chris.Enjoy your holidays

**Comment by brody2consult** [comment]
> Yes.That works perfect.

:+1: Happy to hear thanks!

**Comment by jdnichollsc** [comment]
Any tutorial? I trying with Ionic Framework but I have errors, help me please

**Comment by marcdeveloper** [comment]
@jdnichollsc  If you speak spanish You can see and excellent tutorial in unodepiera.com and a good course in video for  only  around 30€.

**Comment by jdnichollsc** [comment]
@marcdeveloper  thanks but see my example... https://github.com/jdnichollsc/Ionic-Starter-Template ohh is free ;)
