### ISSUE TITLE
Windows bigint problem

### ISSUE THREAD

**Issue by nicolasalcina** [brody2consult/cordova-sqlite-storage#378]
Hello,
we develop an application on android, ios and windows 8.1,
we got a problem happening only in windows 8.1 using bigint in database,
it seems to use only int32
we use it to  implement datetime in unix 1970 format
do you have a solution/fix for that ?
regards 
Nicolas

**Comment by brody2consult** [comment]
Quick fix is to change `sqlite3_bind_int` to `sqlite3_bind_int64` in `src/windows/SQLite3-WinRT/SQLite3/Statement.cpp` and declare the `val` argument as `long long` in `src/windows/SQLite3-WinRT/SQLite3/Statement.[hc]*`. I cannot promise when I will integrate the fix due to my existing backlog and am giving priority to paid work now.

**Comment by nicolasalcina** [comment]
Thanks you it fix my problem, you just forget to tell me the set ;)
Statement.cpp:
  long long Statement::ColumnInt(int index)
  {
    return sqlite3_column_int64(statement, index);
  }
[...]
  int Statement::BindInt(int index, long long val)
  {
    return sqlite3_bind_int64(statement, index, val);
  }

Statement.h:

long long ColumnInt(int index);
[..]
int BindInt(int index, long long val);

I find an another bug in SQLite3.js, line 48, you handle the null but not the undefined:
now it looks like:

```
  args.forEach(function (arg, i) {
    index = i + 1;
    switch (type(arg)) {
      case 'number':
        if (arg % 1 === 0) {
            resultCode = this.statement.bindInt(index, arg);
        } else {
          resultCode = this.statement.bindDouble(index, arg);
        }
        break;
      case 'string':
        resultCode = this.statement.bindText(index, arg);
        break;
      case 'undefined':
      case 'null':
        resultCode = this.statement.bindNull(index);
        break;
      default:
        throw new Error("Unsupported argument type: " + type(arg));
    }
```

Thanks for all

regards Nicolas

**Comment by brody2consult** [comment]
I would like to keep this open until I get a chance to integrate the fixes. Thanks for the correction.

I will have to check what the Web SQL specification says to do when a sql argument is `undefined`, how the Android and iOS versions handle this case, and how the Web SQL built into WebKit handles this case. In general it is better for the application code to use `null` when the parameter should have the NULL value.

**Comment by brody2consult** [comment]
This is now fixed.

**Comment by martatw** [comment]
Hi,

I have downloaded v 0.7.14 and this issue still appears. Do You know when it will be fixed?

**Comment by martatw** [comment]
Hi,

After deeper investigation, I have found out that plugin is inserting correctly bigInt, but when I select it, they are returned as int32 val. Could You please help me to fix it?

**Comment by perez-danilo** [comment]
Why nobody made the change of:
brodybits commented on 30 Oct 2015
and 
synock13 commented on 30 Oct 2015

It fix the problem of int on windows phone

@brodybits 
@synock13 
Thanks
